### ISSUE TITLE
Take units from h5 file when reading

### ISSUE THREAD

**Issue by rettigl** [FAIRmat-NFDI/pynxtools-mpes#3]
Right now, just default units are applied to any h5 file axes, if provided to the dataconverter from the command line. This, however, only works for a few specialized axes names. 
The axes units are however also written to the h5 files as attributes to the axes (/axes/axN/@units). These should be preferably used if available

**Comment by rettigl** [comment]
@domna  I have a fix for this, but I am not allowd to push to this repo...

**Comment by domna** [comment]
> @domna I have a fix for this, but I am not allowd to push to this repo...

You should be able to do it now. I set the correct rights on the repo.
